from inscricao.tests.admin_checkout import *
from inscricao.tests.admin_configuracao import *
from inscricao.tests.admin_participante import *
from inscricao.tests.form_participante import *
from inscricao.tests.model_certificado import *
from inscricao.tests.model_checkout import *
from inscricao.tests.model_configuracao import *
from inscricao.tests.model_participante import *
from inscricao.tests.view_certificado import *
from inscricao.tests.view_inscricao import *
from inscricao.tests.view_notificacao import *
